### ISSUE TITLE
$livePCs is concatenating the strings, instead of adding them to an array.. 

### ISSUE THREAD

**Issue by trickyslip** [cyberautomate/PubPowerShell#1]
I dont have a windows computer to test this on, but I was helping someone with this script and they were seeing behavior where the value of the computer names were being concatenated in the $livePCs variable, as a string, instead of appending to a list as an array. I think you want to add this line before line 45:

$livePCs = @()

This solved the problem for this person, who was using Powershell 5.1 on Windows 2019 server

**Comment by cyberautomate** [comment]
Old issue I just noticed in 2024 lol
